//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppTMA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_planing
    {
        public int Id { get; set; }
        public string planning_Type { get; set; }
        public int planning_Payment { get; set; }
        public int UserId { get; set; }
        public int ClientId { get; set; }
    
        public virtual tbl_Client tbl_Client { get; set; }
        public virtual tbl_user tbl_user { get; set; }
    }
}
