//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppTMA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Complain
    {
        public int Id { get; set; }
        public string complainType { get; set; }
        public System.DateTime complaindata { get; set; }
        public int UserId { get; set; }
    
        public virtual tbl_user tbl_user { get; set; }
    }
}
