//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppTMA.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class File
    {
       
        public int Id { get; set; }
        public string Name { get; set; }
        public DateTime sumitionDate { get; set; }
        public string FilePath { get; set; }
        public string submit_to { get; set; }
        public string submit_from { get; set; }
        
    }
}
