//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppTMA.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TMADBKKEntities6 : DbContext
    {
        public TMADBKKEntities6()
            : base("name=TMADBKKEntities6")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<File> Files { get; set; }
        public virtual DbSet<tbl_Client> tbl_Client { get; set; }
        public virtual DbSet<tbl_Complain> tbl_Complain { get; set; }
        public virtual DbSet<tbl_Notification> tbl_Notification { get; set; }
        public virtual DbSet<tbl_planing> tbl_planing { get; set; }
        public virtual DbSet<tbl_Resources> tbl_Resources { get; set; }
        public virtual DbSet<tbl_Role> tbl_Role { get; set; }
        public virtual DbSet<tbl_SuccessDeplyment> tbl_SuccessDeplyment { get; set; }
        public virtual DbSet<tbl_user> tbl_user { get; set; }
    }
}
